functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров #желательно указать каких именно браузеров, так как их огромное множество
  - Важно, чтобы сайт мог обрабатывать большое количество трафика #большое - это сколько?
  - Сайт должен быть доступен на различных устройствах
 
implicit:
  - Страница сайта не должна перезагружаться при добавлении товара в корзину, применении фильтров, использовании поиска, переходе по страницам в каталоге
  - Пользователь должен иметь возможность удалить товар из корзины 
  - Пользователь должен иметь возможность  оформить заказ с переходом на страницу оплаты
  - Карточка товара на странице товара и в каталоге должна отображать название товара, рейтинг, цену со скидкой и без нее
  - В русскоязычной версии сайта цены должны быть в рублях, а в англоязычной - в долларах.
  - Поьзователь должен иметь возможность зарегистрироваться и авторизоваться, попасть в личный кабинет. 
