---
- summary: |
    Краткое описание тест-кейса. Например, проверка входа пользователя с существующими логином и паролем
  requirement: |
    Тестируемое требование. Например, при верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    Это условия, которые необходимы для проведения тест-кейса. Они должны быть выполнены еще до запуска тест-кейса.
    Например, открыта страница логина
  test-data: |
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку «Войти»
  expected-result: |
    Пользователь должен попасть на главную страницу

# тест-кейс №1
- summary: |
    Добавление товара в корзину
  requirement: |
    Добавляемый товар должен отобразиться на странце корзины
  prerequisites:
    Открыта страница каталога товаров (магазин)
  test-data: |
    
  steps:
    - Нажать кнопку "добавить в корзину" на карточке товара
    - Перейти на страницу корзины
  expected-result: |
    - В каталоге товаров на иконке корзины счетчик товаров увеличился
    - На странице корзины добавленный товар отображается в корзине
---
# тест-кейс №2
- summary: |
    Просмотр подробной информации о товаре
  requirement: |
    Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 
  prerequisites: |
    Открыта страница каталога товаров (магазин)
  test-data: |
  steps:
    - нажать на карточку товара в каталоге товаров
  expected-result: |
    Открылась карточка выбранного товара с названием товара, рейтингом, ценой со скидкой и без скидки
    ---
    # тест-кейс №3
- summary: |
    Фильтрция в каталоге товаров
  requirement: |
     - Пользователь должен иметь возможность фильтровать товары
  prerequisites: |
    Открыта страница каталога товаров (магазин)
  test-data: |
    Тестовые данные
    Категория = smartphones
    В наличии =  true
    Производитель = Apple
    Цена: От 0 до 1000
  steps:
    - установить фильтры согласно тестовым данным
  expected-result: |
    Отобразятся карточки товаров, соответствующие установленным фильтрам 
---
    # тест-кейс №5
- summary: |
    Поиск товара по ключевому слову
  requirement: |
     - Пользователь должен иметь возможность искать товары по ключевому слову 
  prerequisites: |
    Открыта страница каталога товаров (магазин)
  test-data: |
  steps:
    - ввести в поиск "lamp"
  expected-result: |
    Отобразятся карточки товаров, содержащие в названии "lamp"
---   
      # тест-кейс №6
- summary: |
    Поиск товара по категории
  requirement: |
     - Пользователь должен иметь возможность искать товары по категории
  prerequisites: |
    Открыта страница каталога товаров (магазин)
  test-data: |
  steps:
    - ввести в поиск наименование категории "laptops"
  expected-result: |
    Отобразятся карточки товаров, соответвующие категории "laptops"

    Пользователь должен иметь возможность удалить товар из корзины 
---     
    # тест-кейс №7
- summary: |
    Проверка удаления товара из корзины
  requirement: |
     - Пользователь должен иметь возможность удалить товар из корзины 
  prerequisites: |
    Открыта страница корзины, в корзине отображатся как минимум один товар.
  test-data: |
  steps:
    - Нажать кнопку "удалить"
  expected-result: |
    Товар удалится из корзины.
